#notice that file should have name action.yaml
name: 'Get and cache dependencies'
description: 'fetch and cache flutter env and dependencies'
inputs: 
  caching:
    description: 'Wheather dependencies should be cached'
    required: false
    default: 'true'
outputs:
  action-result:
    description: 'The action result'
    value: ${{ steps.job-result.outputs.action-status }}
runs: 
  using: 'composite'
  steps:
     - name: Inputs check
       run: echo ${{ inputs.caching }}
       shell: bash   
     - name: Cache Flutter
       if: inputs.caching == 'true'
       id: cache_flutter
       uses: actions/cache@v3
       with:
         path: /Users/runner/hostedtoolcache/flutter/stable-3.27.4-arm64
         key: flutter-sdk-${{ runner.os }}-3.27.4
          
     - name: Cache pub dependencies
       if: inputs.caching == 'true'
       id: cache_pub
       uses: actions/cache@v3
       with:
         path: /Users/runner/.pub-cache
         key: pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
         restore-keys: |
           pub-cache-${{ runner.os }}-
          
     - name: Set Up Flutter
       uses: subosito/flutter-action@v2
       with:
        flutter-version: '3.27.4'
        channel: 'stable'
        cache: false
         
     - name: Install dependencies
       if: steps.cache_pub.outputs.cache-hit != 'true' ||  inputs.caching != 'true'
       run: flutter pub get
       shell: bash         # required for run command in actions

     - name: Set job result
       id: job-result
       continue-on-error: true
       run: "action-status=${{job.status}}" >> $GITHUB_OUTPUT
       shell: bash 

    - name: check outputs
      run: echo ${{ steps.job-result.outputs.action-status }}
      shell: bash

