name: Evn vars
on:
   workflow_dispatch:
   issues: 
     types: 
      - opened 
      - closed
   pull_request:
     branches:
     - main
     - 'feature/**'
     types:
      - opened
      - edited
      
jobs:
  env-vars:
    runs-on: ubuntu-latest
    outputs: 
        readme-file: ${{ steps.publish_output_id.outputs.readme-file-first }}
    steps:
      - name: first var
        run: echo "${{ toJSON(github.event) }}"
      - name: Find and export first README.md
        id: publish_output_id 
        run: |
          find README.md
           
          # # list them for debug
          # echo "All README.md files:"
          # pwd
          # find /README.md

          # # take only the first one
          # file=$( find ./README.md )
          # if [ -n "$file" ]; then
          #   # strip leading "./" and export
          #   rel=${file#./}
          #   echo "readme-file-first=${rel}" >> "$GITHUB_OUTPUT"
          #   echo "Exported readme-file-first=${rel}"
          # else
          #   echo "No README.md found, skipping export."
          # fi
        
  
   
  another-job-name:
     runs-on: ubuntu-latest
     needs: env-vars
     steps:
      - name: output file name
        run: echo ${{ needs.env-vars.outputs.readme-file }}

