name: Evn vars
on:
   workflow_dispatch:
   issues: 
     types: 
      - opened 
      - closed
   pull_request:
     branches:
     - main
     - 'feature/**'
     types:
      - opened
      - edited
env:
   GLOBAL-ENV-VAR: 'variable which is available for all jobs'
jobs:
  env-vars:  # job name
    env:
        LOCAL-ENV-VAR: 'variable which is available for env-vars job'
    runs-on: ubuntu-latest
    outputs: 
        readme-file: ${{ steps.publish_output_id.outputs.readme-file-first }}
    steps:
      - name: Check global var
        run: echo "${{ env.GLOBAL-ENV-VAR }}"
      - name: Check local var
        run: echo "${{ env.LOCAL-ENV-VAR }}"
      - name: Check secret var
        run: echo "${{ secrets.API_KEY }}"
      - name: first var
        run: echo "${{ toJSON(github.event) }}"
      - name: checkout project
        uses: actions/checkout@v4    
      - name: Find and export first README.md
        id: publish_output_id 
        run: |
          
          # list them for debug
          echo "All README.md files:"
          find README.md
  
          # take only the first one
            file=$( find README.md )
            if [ -n "$file" ]; then
            # strip leading "./" and export
            rel=${file#./}
            echo "readme-file-first=${rel}" >> "$GITHUB_OUTPUT"
            echo "Exported readme-file-first=${rel}"
          else
            echo "No README.md found, skipping export."
          fi
        
  
   
  another-job-name:
     runs-on: ubuntu-latest
     needs: env-vars
     environment: dev
     steps:
      - name: output file name
        run: echo ${{ needs.env-vars.outputs.readme-file }}
      - name: secrets from environment
        run: echo ${{ secrets.API_KEY }}
      - name: secrets from environment 2
        run: echo ${{ secrets.ANOTHER_API_KEY }}

