name: Evn vars
on:
   workflow_dispatch:
   issues: 
     types: 
      - opened 
      - closed
   pull_request:
     branches:
     - main
     - 'feature/**'
     types:
      - opened
      - edited
      
jobs:
  env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: first var
        run: echo "${{ toJSON(github.event) }}"

