name: Deploy reusable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: false
        description: name of deploying artifact
        default: android_release
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ artifact-name }}
      - name: list files
        run: ls  
      - name: deploy
        run: echo 'deloying..'
        
          
      
