name: Reusable job
on: 
  workflow_call:
    outputs:
      artifact-name:
        value: ${{ jobs.fetch-flutter.outputs.job-result }}

jobs:
  fetch-flutter:
    runs-on: ubuntu-latest

    outputs: 
      job-result: ${{ steps.artifact_name_id.outputs.artifact-name }}
    steps:
      - name: fetch project
        uses: actions/checkout@v3
      
      - name: fetch dependencies
        uses: ./.github/actions/flutter_dependencies

        
      - name: Build release
        run: flutter build apk --release  
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4 
        with:
          name: android_release
          path:
            build/app/outputs/flutter-apk/**.apk
            
      - name: write workflow result
        id: artifact_name_id
        run: echo "artifact-name=android_release" >> "$GITHUB_OUTPUT"



        
