name: Reusable job
on: 
  workflow_call:
    outputs:
      artifact-name:
        value: ${{ jobs.fetch-flutter.outputs.job-result }}

jobs:
  fetch-flutter:
    runs-on: ubuntu-latest

    outputs: 
      job-result: ${{ steps.artifact_name_id.outputs.artifact-name }}
    steps:
      # - name: fetch project
      #   uses: actions/checkout@v3
      
      # - name: Cache Flutter
      #   id: cache_flutter
      #   uses: actions/cache@v3
      #   with:
      #    path: /Users/runner/hostedtoolcache/flutter/stable-3.27.4-arm64
      #    key: flutter-sdk-${{ runner.os }}-3.27.4
          
      # - name: Cache pub dependencies
      #   id: cache_pub
      #   uses: actions/cache@v3
      #   with:
      #    path: /Users/runner/.pub-cache
      #    key: pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
      #    restore-keys: |
      #      pub-cache-${{ runner.os }}-
          
      # - name: Set Up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #    flutter-version: '3.27.4'
      #    channel: 'stable'
      #    cache: false
         
      # - name: Install dependencies
      #   if: steps.cache_pub.outputs.cache-hit != 'true'
      #   run: flutter pub get

      # - name: Build release
      #   run: flutter build apk --release  
        
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4 
      #   with:
      #     name: android_release
      #     path:
      #       build/app/outputs/flutter-apk/**.apk
            
      - name: write workflow result
        id: artifact_name_id
        run: echo "artifact-name=android_release" >> "$GITHUB_OUTPUT"

  check-output-job:
        runs-on: ubuntu-latest
        needs: fetch-flutter
        steps:
          - name: check
            run: echo ${{ needs.fetch-flutter.outputs.job-result }}
          

        
