name: Git action
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello world"
          echo "Bye world"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "scond job"
        
          
