name: Use reusable workflow
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/reusable.yaml
    
  check-otput:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: check ouput
        run: echo ${{ needs.build.outputs.artifact-name }}  
    
  deploy:
    needs: build
    uses: ./.github/workflows/reusable_deploy.yaml
    with: 
       artifact-name: ${{ needs.build.outputs.artifact-name }}
    secrets:
      some-secret: ${{secrets.API_KEY}}
    
      
