name: Use reusable workflow
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/reusable.yaml
    
  deploy:
    needs: build
    uses: ./.github/workflows/reusable_deploy.yaml
    with: 
       artifact-name: ${{ needs.build.otputs.artifact-name }}
    secrets:
      some-secret: ${{secrets.API_KEY}}
    
      
